### ISSUE TITLE
[IGNORE] User was using old version of node

### ISSUE THREAD

**Issue by sbellem** [drand/drandjs#12]
**CORRECTION**: The node version I was using was 9.6.1, because I was using a docker image that had already been pulled a good while ago :smile:. I overlooked this and thought I was using the latest version (13).

---

~~It may be useful to add an "easy-to-see" note in the README that emphasizes that node 12 is required. Although one can see that the CircleCI config does use a node 12 image, a notice on the README would be helpful. With node 13 the following error occurs (the root of the problem is in `noble-bls12-381`):~~

```node
/usr/src/node_modules/@nikkolasg/noble-bls12-381/lib/index.js:19
exports.G1 = new point_1.Point(new fp_1.Fp(3685416753713387016781088315183077757961620795782546409894578378688607592378376318836054947676345821548104185464507n), new fp_1.Fp(13395065449
44476473020471379941921221584933875938349620426543736416511423956333506472724655353366534992391756441569n), new fp_1.Fp(1n), fp_1.Fp);
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sbellem** [comment]
Apologies. I rarely work with node, and I was using an old image/version of node (v9.6.1). Closing!

**Comment by sbellem** [comment]
Since this issue may be misleading, an admin may wish to [delete the issue](https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue).

In the time being, I'll edit the title of the issue.

/cc @nikkolasg

**Comment by nikkolasg** [comment]
No worries !
